"""Run python3 build.py after editing site-config.json. No dependencies required."""
import base64, html, json
from pathlib import Path
ROOT = Path(__file__).resolve().parent
C = json.loads((ROOT / 'site-config.json').read_text())
B, T = C['company'], C['copy']
def e(v): return html.escape(str(v), quote=True)
def lines(v): return e(v).replace('\n', '<br>')
def icon(name):
    paths = {'building':'M4 21V5h10v16M14 11h6v10M2 21h20M7 8h4M7 12h4M7 16h4M17 14h1M17 18h1', 'road':'M7 3L3 21M17 3l4 18M12 3v3m0 4v4m0 4v3', 'pipe':'M3 3h6v7h9v-3h4v10H8v5H2V10h1z', 'bolt':'M13 2L4 14h7l-1 8 10-13h-8z', 'tools':'M14 4a6 6 0 0 0-7 8l-5 6 4 4 6-6a6 6 0 0 0 8-7l-4 4-5-5z', 'shield':'M12 2l9 4v7c-1 5-9 9-9 9s-8-4-9-9V6zM7 12l3 3 7-7', 'clock':'M12 7v5l4 2M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0', 'handshake':'M2 8l5-4 5 3 5-3 5 4-4 11-5 2-9-7M7 8l4-1 7 7M6 15l5 4', 'people':'M8 10a4 4 0 1 0 0-8 4 4 0 0 0 0 8M1 22v-4a7 7 0 0 1 14 0v4M16 3a4 4 0 0 1 0 8M18 15a5 5 0 0 1 5 5v2'}
    return f'<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="{paths.get(name,paths["building"])}"/></svg>'
def photo(key, cls='', eager=False):
    i=C['images'][key]
    # Generic licensed stock photos, not photographs of the named company projects.
    return f'<img class="{cls}" src="{e(i["url"])}" alt="{e(i["alt"])}" loading="{"eager" if eager else "lazy"}" decoding="async" width="1200" height="800"'+(' fetchpriority="high"' if eager else '')+'>'
def button(label,href,cls='primary'): return f'<a class="button {cls}" href="{e(href)}">{e(label)} <span aria-hidden="true">↗</span></a>'
def eyebrow(text): return f'<p class="eyebrow">{e(text)}</p>'
def pagehero(key):
    p=C['pages'][key]
    return f'<section class="page-hero"><div class="wrap"><div class="breadcrumb"><a href="index.html">Home</a><span>/</span>{e(next(n["label"] for n in C["nav"] if n["id"]==key))}</div>{eyebrow(p["eyebrow"])}<h1>{lines(p["heading"])}</h1><p class="lead">{e(p["intro"])}</p></div><span class="hero-line" aria-hidden="true"></span></section>'
def nav(key,footer=False): return ''.join(f'<a href="{n["file"]}"'+(' aria-current="page"' if n['id']==key else '')+f'>{e(n["label"])}</a>' for n in C['nav'])
def header(key): return f'''<a class="skip" href="#main">Skip to content</a><div class="topbar"><div class="wrap"><a class="top-address" href="{e(B['directions'])}">{e(B['address'])}</a><a class="phone" href="{B['phoneHref']}">☎ {e(B['phone'])}</a></div></div><header class="site-header"><div class="wrap navigation"><a class="brand" href="index.html" aria-label="{e(B['name'])} home"><img class="full-logo" src="{B['logo']}" alt="{e(B['name'])} — {e(B['tagline'])}" width="1178" height="224"><img class="mobile-logo" src="{B['emblem']}" alt="Al Furqan globe emblem" width="64" height="64"><span class="mobile-brand">{e(B['shortName'])}<small>{e(B['tagline'])}</small></span></a><button class="menu-toggle" aria-expanded="false" aria-controls="main-nav" aria-label="Open navigation"><span></span><span></span><span></span></button><nav id="main-nav" aria-label="Main navigation">{nav(key)}{button(T['quote'],'contact.html','gold')}</nav></div></header>'''
def cta(): return f'<section class="cta-strip"><div class="wrap"><div>{eyebrow(B["tagline"])}<h2>{lines(T["ctaHeading"])}</h2><p>{e(T["ctaBody"])}</p></div>{button(T["quote"],"contact.html","gold")}</div></section>'
def footer(key): return f'''<footer><div class="wrap footer-grid"><div class="footer-brand"><a href="index.html" class="logo-tile"><img src="{B['logo']}" alt="{e(B['name'])} — Government Contractors" width="1178" height="224" loading="lazy"></a><p class="footer-tagline">{e(T['footerNote'])}</p><p>Construction & engineering<br>Lahore, Punjab, Pakistan</p></div><div><h2>Explore</h2><nav aria-label="Footer navigation">{nav(key)}</nav></div><div><h2>Services</h2>{''.join(f'<a href="services.html#{s["id"]}">{e(s["name"])}</a>' for s in C['services'])}</div><div><h2>Contact our office</h2><address>{e(B['address'])}</address><a class="footer-phone" href="{B['phoneHref']}">{e(B['phone'])}</a><a href="mailto:{e(B['email'])}">{e(B['email'])}</a><small>{'Placeholder email' if B['emailIsPlaceholder'] else ''}</small></div></div><div class="wrap footer-bottom"><span>© 2026 {e(B['name'])}. {e(T['footerLegal'])}</span><a href="#top">Back to top ↑</a></div></footer>'''
def servicecards(): return '<div class="service-grid">'+''.join(f'<a class="service-card reveal" href="services.html#{s["id"]}"><span class="icon-box">{icon(s["icon"])}</span><h3>{e(s["name"])}</h3><p>{e(s["description"])}</p><span class="card-link">Explore service ↗</span></a>' for s in C['services'])+'</div>'
def projectcard(p):
    return f'<article class="project-card reveal" data-category="{e(p["category"])}"><button class="project-open" data-project="{p["id"]}" aria-label="View {e(p["title"])} project details"><div class="project-image">{photo(p["images"][0])}<span class="photo-badge">{e(T["photoLabel"] if C["images"][p["images"][0]].get("generic", True) else T["companyPhotoLabel"])}</span></div><div class="project-copy"><span class="category">{e(p["category"])}</span><h3>{e(p["title"])} <span aria-hidden="true">↗</span></h3><p class="location">{e(p["location"])}</p><p>{e(p["description"])}</p></div></button></article>'
def projectgrid(featured=False): return '<div class="project-grid">'+''.join(projectcard(p) for p in C['projects'] if not featured or p['featured'])+'</div>'
def dialog(): return f'<dialog id="project-dialog" aria-labelledby="dialog-title"><button class="dialog-close" aria-label="{e(T["close"])}">✕</button><div id="dialog-content"></div></dialog>'
def node(n,mobile=False):
    label=(f'<strong>{e(n["name"])}</strong>' if n.get('name') else '')+f'<span>{e(n["role"])}</span>'+(f'<small>{e(n["note"])}</small>' if n.get('note') else '')
    ext=' external' if n.get('external') else ''
    if mobile:
        if n.get('children'):return f'<li><details class="org-accordion{ext}" open><summary>{label}</summary><ul>'+''.join(node(x,True) for x in n['children'])+'</ul></details></li>'
        return f'<li><div class="org-card{ext}">{label}</div></li>'
    return f'<li><div class="org-card{ext}">{label}</div>'+('<ul>'+''.join(node(x) for x in n['children'])+'</ul>' if n.get('children') else '')+'</li>'
def organogram():
    o=C['organogram']; leaders=''.join(node(n) for n in o['leaders'])
    branches=''.join(f'<div class="org-branch"><h3>{e(b["label"])}</h3><ul class="org-tree">'+''.join(node(n) for n in b['children'])+'</ul></div>' for b in o['branches'])
    mobile=''.join(f'<details class="org-mobile-branch" open><summary>{e(b["label"])}</summary><ul>'+''.join(node(n,True) for n in b['children'])+'</ul></details>' for b in o['branches'])
    return f'<div class="org-chart"><ul class="org-leaders">{leaders}</ul><div class="org-desktop">{branches}</div><div class="org-mobile">{mobile}</div><div class="org-legend"><span><i></i>{e(T["legendInternal"])}</span><span><i class="external"></i>{e(T["legendExternal"])}</span></div></div>'
def home():
    p=C['pages']['home']
    stats=''.join(f'<div><strong>{e(s["value"])}</strong><span>{e(s["label"])}</span>'+('<small>Placeholder</small>' if s['placeholder'] else '<small>Established experience</small>')+'</div>' for s in C['stats'])
    return f'''<section class="home-hero"><div class="hero-copy">{eyebrow(p['eyebrow'])}<h1>{lines(p['heading'])}</h1><h2>{e(p['intro'])}</h2><p>{e(p['body'])}</p><div class="button-row">{button(T['quote'],'contact.html','gold')}{button(T['viewProjects'],'projects.html','outline-light')}</div><div class="hero-bottom"><span class="gold-rule"></span>{e(B['experience'])}</div></div><div class="hero-photo">{photo('construction','',True)}<div class="hero-logo"><img src="{B['logo']}" alt="{e(B['name'])} — Government Contractors" width="1178" height="224"></div><span class="hero-caption">{e(T['photoLabel'])} · Construction</span></div></section><section class="stats wrap" aria-label="Company at a glance">{stats}</section><section class="section wrap"><div class="section-head"><div>{eyebrow('01 / Capabilities')}<h2>{lines(T['homeServicesHeading'])}</h2></div><p>{e(T['homeServicesBody'])}</p></div>{servicecards()}</section><section class="section soft"><div class="wrap split"><div class="about-photo">{photo('lahore')}<div class="experience-box"><strong>30+</strong><span>Years of<br>experience</span></div><span class="image-caption">Lahore, Pakistan · Local context</span></div><div>{eyebrow('02 / About Al Furqan')}<h2>{lines(T['homeAboutHeading'])}</h2><p>{e(T['homeAboutBody'])}</p><p>{e(C['pages']['about']['body'])}</p>{button(T['learnMore'],'about.html')}</div></div></section><section class="section wrap"><div class="section-head"><div>{eyebrow('03 / Selected projects')}<h2>{e(T['homeProjectsHeading'])}</h2></div>{button(T['allProjects'],'projects.html','text-button')}</div>{projectgrid(True)}<p class="small-note">{e(T['projectNote'])}</p></section>{cta()}{dialog()}'''
def about():
    return pagehero('about')+f'''<section class="section wrap split"><div>{eyebrow(B['tagline'])}<h2>{lines(T['aboutProfileHeading'])}</h2><p>{e(C['pages']['about']['body'])}</p><p>{e(T['aboutProfileBody'])}</p><p class="small-note">Established: {e(B['established'])} · Exact year to be confirmed</p></div><div class="about-photo">{photo('lahore')}<span class="image-caption">Lahore, Pakistan · Local context</span></div></section><section class="section soft"><div class="wrap vision-grid"><article>{eyebrow('Our vision')}<h2>Building for the future.</h2><p>{e(C['vision'])}</p></article><article>{eyebrow('Our mission')}<h2>Delivering with purpose.</h2><p>{e(C['mission'])}</p></article></div></section><section class="section wrap"><div class="section-head"><div>{eyebrow('Our core values')}<h2>{e(T['valuesHeading'])}</h2></div></div><div class="values-grid">{''.join(f'<article class="value-card reveal">{icon(v["icon"])}<h3>{e(v["title"])}</h3><p>{e(v["text"])}</p></article>' for v in C['values'])}</div></section><section class="section soft" id="team"><div class="wrap"><div class="section-head"><div>{eyebrow('Our team & structure')}<h2>{lines(T['teamHeading'])}</h2></div><p>{e(T['teamIntro'])}</p></div>{organogram()}</div></section>{cta()}'''
def services():
    rows=''.join(f'<article class="service-detail" id="{s["id"]}"><div class="service-detail-image">{photo(s["image"])}</div><div><span class="service-number">0{i+1}</span><h2>{e(s["name"])}</h2><p>{e(s["description"])}</p><p>{e(s["detail"])}</p><ul class="checklist">'+''.join(f'<li>{e(x)}</li>' for x in s['scope'])+f'</ul>{button(T["quote"],"contact.html?service="+s["id"],"text-button")}</div></article>' for i,s in enumerate(C['services']))
    return pagehero('services')+f'<section class="section wrap"><p class="section-intro">{e(C["pages"]["services"]["body"])}</p>{rows}</section><section class="section soft"><div class="wrap"><h2>{e(T["processHeading"])}</h2><div class="process-grid">'+''.join(f'<article><span class="service-number">0{i+1}</span><h3>{e(p["title"])}</h3><p>{e(p["text"])}</p></article>' for i,p in enumerate(C['process']))+f'</div></div></section>{cta()}'
def projects():
    filters=f'<button class="filter active" data-filter="all" aria-pressed="true">{e(T["allFilter"])}</button>'+''.join(f'<button class="filter" data-filter="{e(c)}" aria-pressed="false">{e(c)}</button>' for c in C['categories'])
    return pagehero('projects')+f'<section class="section wrap"><p class="section-intro">{e(C["pages"]["projects"]["body"])}</p><div class="filters" role="group" aria-label="Filter projects by category">{filters}</div><p id="project-count" class="small-note" role="status" aria-live="polite">6 projects</p>{projectgrid()}<p class="small-note">{e(T["projectNote"])}</p></section>{cta()}{dialog()}'
def credentials():
    return pagehero('credentials')+f'<section class="section wrap"><p class="section-intro">{e(C["pages"]["credentials"]["body"])}</p><h2>{e(T["credentialsHeading"])}</h2><p>{e(T["credentialNote"])}</p><div class="clients-grid">'+''.join(f'<article class="client-placeholder"><span class="pending">Logo placeholder</span><strong>{e(c["name"])}</strong><p>{e(c["description"])}</p></article>' for c in C['clients'])+f'</div></section><section class="section soft"><div class="wrap"><h2>{e(T["registrationsHeading"])}</h2><div class="credential-grid">'+''.join(f'<article class="credential-card">{icon("shield")}<span class="pending">To be confirmed</span><h3>{e(c["title"])}</h3><p>{e(c["value"])}</p><p class="small-note">{e(c["detail"])}</p></article>' for c in C['credentials'])+f'</div></div></section>{cta()}'
def contact():
    l=T['formLabels']; options=''.join(f'<option value="{s["id"]}">{e(s["name"])}</option>' for s in C['services'])
    return pagehero('contact')+f'''<section class="section wrap contact-grid"><div class="form-panel"><h2>{e(T['contactFormHeading'])}</h2><p class="form-notice">{e(T['contactPlaceholderNote'])}</p><form id="enquiry-form"><div class="form-row"><label>{e(l['name'])} *<input name="name" autocomplete="name" required maxlength="100"></label><label>{e(l['phone'])} *<input name="phone" type="tel" autocomplete="tel" required maxlength="40"></label></div><label>{e(l['email'])} *<input name="email" type="email" autocomplete="email" required maxlength="160"></label><label>{e(l['service'])} *<select name="service" required><option value="">{e(l['select'])}</option>{options}</select></label><label>{e(l['message'])} *<textarea name="message" rows="5" required maxlength="4000" placeholder="{e(l['hint'])}"></textarea></label><button type="submit" class="button primary">{e(T['formButton'])} <span aria-hidden="true">↗</span></button><div id="form-result" hidden><p id="form-status" role="status" aria-live="polite"></p><label>Email draft<textarea id="draft" readonly rows="8"></textarea></label><div class="button-row"><a class="button primary" id="email-draft" href="#">Open email app ↗</a><button class="button secondary" id="copy-enquiry" type="button">{e(T['copyButton'])}</button></div></div></form></div><aside class="office-details"><h2>{e(T['contactOfficeHeading'])}</h2><div class="contact-block"><span class="contact-icon">⌖</span><div><h3>{e(T['addressLabel'])}</h3><address>{e(B['address'])}</address></div></div><div class="contact-block"><span class="contact-icon">☎</span><div><h3>{e(T['phoneLabel'])}</h3><a class="office-phone" href="{B['phoneHref']}">{e(B['phone'])}</a></div></div><div class="contact-block"><span class="contact-icon">@</span><div><h3>{e(T['emailLabel'])}</h3><a href="mailto:{e(B['email'])}">{e(B['email'])}</a></div></div><div class="contact-block"><span class="contact-icon">◷</span><div><h3>{e(T['officeHours'])}</h3><p>{e(B['hours'])}</p></div></div>'''+(button('WhatsApp','https://wa.me/'+B['whatsapp'],'secondary') if B['whatsapp'] else f'<button class="button secondary" disabled>{e(T["whatsappPending"])}</button>')+f'''</aside></section><section class="wrap map-section"><iframe src="{e(B['mapEmbed'])}" title="Map showing Khawaja Arcade, Wahdat Road, Muslim Town, Lahore" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe><div class="map-caption"><p>Khawaja Arcade · Muslim Town · Lahore</p>{button(T['directions'],B['directions'],'text-button')}</div></section><section class="section wrap faq"><h2>{e(T['faqHeading'])}</h2>{''.join(f'<details><summary>{e(q["q"])}</summary><p>{e(q["a"])}</p></details>' for q in T['faq'])}</section>'''
schema={'@context':'https://schema.org','@type':'GeneralContractor','name':B['name'],'url':B['url'],'telephone':B['phone'],'logo':B['url']+'/logo.svg','address':{'@type':'PostalAddress','streetAddress':B['streetAddress'],'addressLocality':'Lahore','addressRegion':'Punjab','postalCode':'54700','addressCountry':'PK'},'areaServed':{'@type':'City','name':'Lahore'},'description':C['pages']['home']['description']}
renderers={'home':home,'about':about,'services':services,'projects':projects,'credentials':credentials,'contact':contact}
colors=C['palette']; cssvars=':root{'+''.join(f'--{k}:{colors[v]};' for k,v in [('primary','primary'),('primary-light','primaryLight'),('navy','navy'),('accent','accent'),('bg-light','bgLight'),('text','text')])+'}'
(ROOT/'brand.css').write_text('/* Colors sampled from the supplied logo; see site-config.json. */\n'+cssvars)
(ROOT/'site-config.js').write_text('// Generated from site-config.json by build.py; edit the JSON source.\nwindow.SITE = '+json.dumps(C,ensure_ascii=False)+';')
for n in C['nav']:
    key=n['id']; p=C['pages'][key]; url=B['url']+'/'+('' if key=='home' else n['file'])
    page=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="{colors['navy']}"><title>{e(p['title'])} | {e(B['name'])}</title><meta name="description" content="{e(p['description'])}"><link rel="canonical" href="{e(url)}"><meta property="og:type" content="website"><meta property="og:locale" content="en_PK"><meta property="og:title" content="{e(p['title'])} | {e(B['name'])}"><meta property="og:description" content="{e(p['description'])}"><meta property="og:url" content="{e(url)}"><meta property="og:image" content="{B['url']}/logo-original.png"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="emblem.svg" type="image/svg+xml"><link rel="stylesheet" href="brand.css?v=20260925-projects"><link rel="stylesheet" href="styles.css?v=20260925-projects"><link rel="preconnect" href="https://images.pexels.com"><script type="application/ld+json">{json.dumps(schema,ensure_ascii=False)}</script><script defer src="site-config.js?v=20260925-projects"></script><script defer src="app.js?v=20260925-projects"></script></head><body id="top" data-page="{key}">{header(key)}<main id="main">{renderers[key]()}</main>{footer(key)}</body></html>'''
    (ROOT/n['file']).write_text(page)
# SVG viewport wrappers preserve the raster artwork; they do not redraw the mark.
png=base64.b64encode((ROOT/'logo-clean.png').read_bytes()).decode()
for filename,viewbox in [('logo.svg','45 145 2090 400'),('emblem.svg','40 145 390 390')]:
    (ROOT/filename).write_text(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{viewbox}"><image width="2170" height="725" href="data:image/png;base64,{png}"/></svg>')
(ROOT/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: '+B['url']+'/sitemap.xml\n')
(ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+B['url']+'/'+('' if n['id']=='home' else n['file'])+'</loc></url>' for n in C['nav'])+'</urlset>')
(ROOT/'CNAME').write_text('alfurqanengineers.com\n')
(ROOT/'.nojekyll').touch()
print('Built six pages, shared config, brand CSS, logo wrappers and sitemap.')
